from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .validation import Finding


@dataclass(frozen=True)
class SemanticRuleSet:
    name: str
    description: str


RULESETS = {
    "agent_script_contract": SemanticRuleSet(
        "agent_script_contract", "Agent-generated Earth Engine script structure and safety contract."
    ),
    "optical_index": SemanticRuleSet("optical_index", "Generic optical index workflow."),
    "vegetation_index_ndvi": SemanticRuleSet("vegetation_index_ndvi", "NDVI optical index workflow."),
    "water_index_ndwi": SemanticRuleSet("water_index_ndwi", "NDWI/MNDWI optical water index workflow."),
    "builtup_index_ndbi": SemanticRuleSet("builtup_index_ndbi", "NDBI optical built-up index workflow."),
    "sentinel2_ndvi_monthly_zonal": SemanticRuleSet(
        "sentinel2_ndvi_monthly_zonal", "Sentinel-2 NDVI monthly composite/zonal statistics."
    ),
    "landsat_lst": SemanticRuleSet("landsat_lst", "Landsat Collection 2 LST workflow."),
    "landsat_c2_lst": SemanticRuleSet("landsat_c2_lst", "Backward-compatible alias for landsat_lst."),
    "sentinel1_flood_before_after": SemanticRuleSet(
        "sentinel1_flood_before_after", "Sentinel-1 before/after flood workflow."
    ),
    "export_table_csv": SemanticRuleSet("export_table_csv", "Export.table.toDrive CSV export."),
    "dynamic_world_landcover_ndvi": SemanticRuleSet(
        "dynamic_world_landcover_ndvi", "Dynamic World land-cover-aware Sentinel-2 NDVI diagnostics."
    ),
    "dynamic_world_landcover": SemanticRuleSet(
        "dynamic_world_landcover", "Dynamic World land-cover summary workflow."
    ),
    "export_image_geotiff": SemanticRuleSet("export_image_geotiff", "Export.image.toDrive GeoTIFF export."),
}


def infer_semantic_rulesets(text: str, explicit: str | None = None) -> list[str]:
    if explicit:
        return [item.strip() for item in explicit.split(",") if item.strip()]
    lower = text.lower()
    rules: list[str] = []
    if "generated by gee-agent-skill" in lower or "gee_skill" in lower:
        rules.append("agent_script_contract")
    if "normalizeddifference" in lower or "expression(" in lower:
        rules.append("optical_index")
    if (
        "copernicus/s2_sr_harmonized" in lower
        and "ndvi" in lower
        and ("reduceregions" in lower or "build_16day_statistics" in lower or "hk_january" in lower)
    ):
        rules.append("sentinel2_ndvi_monthly_zonal")
        rules.append("vegetation_index_ndvi")
    elif "ndvi" in lower:
        rules.append("vegetation_index_ndvi")
    if "ndwi" in lower or "mndwi" in lower:
        rules.append("water_index_ndwi")
    if "ndbi" in lower:
        rules.append("builtup_index_ndbi")
    if "landsat/" in lower and ("st_b10" in lower or "lst" in lower):
        rules.append("landsat_lst")
    if "copernicus/s1_grd" in lower or ("sentinel-1" in lower and "flood" in lower):
        rules.append("sentinel1_flood_before_after")
    if "export.table.todrive" in lower or "ee.batch.export.table.todrive" in lower:
        rules.append("export_table_csv")
    if "export.image.todrive" in lower or "ee.batch.export.image.todrive" in lower:
        rules.append("export_image_geotiff")
    if "google/dynamicworld/v1" in lower:
        rules.append("dynamic_world_landcover_ndvi" if "ndvi" in lower else "dynamic_world_landcover")
    return rules


def validate_semantics(path: Path, rulesets: list[str] | None = None) -> list[Finding]:
    text = path.read_text(encoding="utf-8")
    lower = text.lower()
    selected = rulesets or infer_semantic_rulesets(text)
    findings: list[Finding] = []
    for ruleset in selected:
        if ruleset == "agent_script_contract":
            findings.extend(_agent_script_contract(text, lower))
        elif ruleset == "optical_index":
            findings.extend(_optical_index(text, lower))
        elif ruleset == "vegetation_index_ndvi":
            findings.extend(_vegetation_index_ndvi(text, lower))
        elif ruleset == "water_index_ndwi":
            findings.extend(_water_index_ndwi(text, lower))
        elif ruleset == "builtup_index_ndbi":
            findings.extend(_builtup_index_ndbi(text, lower))
        elif ruleset == "sentinel2_ndvi_monthly_zonal":
            findings.extend(_sentinel2_ndvi(text, lower))
        elif ruleset in {"landsat_lst", "landsat_c2_lst"}:
            findings.extend(_landsat_lst(text, lower, ruleset="landsat_lst" if ruleset == "landsat_c2_lst" else ruleset))
        elif ruleset == "sentinel1_flood_before_after":
            findings.extend(_sentinel1_flood(text, lower))
        elif ruleset == "export_table_csv":
            findings.extend(_export_table_csv(text, lower))
        elif ruleset == "export_image_geotiff":
            findings.extend(_export_image_geotiff(text, lower))
        elif ruleset == "dynamic_world_landcover_ndvi":
            findings.extend(_dynamic_world_landcover_ndvi(text, lower))
        elif ruleset == "dynamic_world_landcover":
            findings.extend(_dynamic_world_landcover(text, lower))
        else:
            findings.append(Finding("warning", "unknown-semantic-ruleset", f"Unknown ruleset: {ruleset}", ruleset=ruleset))
    if selected and not any(item.severity == "error" for item in findings):
        findings.append(
            Finding(
                "info",
                "semantic-validation-ok",
                f"Semantic rules passed: {', '.join(selected)}",
            )
        )
    return findings


def _require(
    condition: bool,
    ruleset: str,
    code: str,
    message: str,
    category: str,
    hint: str | None = None,
    retryable: bool = False,
) -> list[Finding]:
    if condition:
        return []
    return [
        Finding(
            "error",
            code,
            message,
            hint=hint,
            category=category,
            rule_id=f"{ruleset}.{code}",
            ruleset=ruleset,
            retryable=retryable,
        )
    ]


def _agent_script_contract(text: str, lower: str) -> list[Finding]:
    ruleset = "agent_script_contract"
    findings: list[Finding] = []
    findings += _require(
        "ee.authenticate(" not in lower,
        ruleset,
        "no-inline-authenticate",
        "Generated scripts must not call ee.Authenticate(); authentication belongs to the CLI/user environment.",
        "AUTH_ERROR",
        hint="Run earthengine authenticate outside the generated script.",
    )
    if "ee.initialize(" in lower:
        findings.append(
            Finding(
                "warning",
                "inline-initialize",
                "Generated scripts should normally avoid inline ee.Initialize() unless explicitly requested.",
                hint="Prefer CLI/runtime initialization so project and credentials are controlled outside the script.",
                category="PROJECT_ERROR",
                rule_id=f"{ruleset}.inline-initialize",
                ruleset=ruleset,
                retryable=True,
            )
        )
    if "filterdate" in lower:
        has_standard_window = ("START_DATE" in text or "DATE_START" in text) and (
            "END_DATE" in text or "DATE_END" in text
        )
        has_before_after_windows = all(
            constant in text
            for constant in ("BEFORE_START", "BEFORE_END", "AFTER_START", "AFTER_END")
        )
        findings += _require(
            has_standard_window or has_before_after_windows,
            ruleset,
            "date-window-constants",
            "Generated scripts with filterDate should expose reviewed date-window constants.",
            "VALIDATION_ERROR",
        )
    if "ee.imagecollection(" in lower:
        findings += _require(
            "DATASET_ID" in text,
            ruleset,
            "dataset-id-constant",
            "Generated scripts using ImageCollection should expose a DATASET_ID constant.",
            "DATASET_NOT_FOUND",
        )
    has_export = "export." in lower or "ee.batch.export" in lower
    has_table_export = "export.table.todrive" in lower or "ee.batch.export.table.todrive" in lower
    has_image_export = "export.image.todrive" in lower or "ee.batch.export.image.todrive" in lower
    if has_export:
        for constant, code in (
            ("SCALE", "scale-constant"),
            ("CRS", "crs-constant"),
            ("EXPORT_DESCRIPTION", "export-description-constant"),
        ):
            findings += _require(
                constant in text,
                ruleset,
                code,
                f"Generated export scripts should expose {constant}.",
                "VALIDATION_ERROR" if constant != "SCALE" else "REDUCER_SCALE_ERROR",
            )
        if has_table_export:
            findings += _require(
                "selectors=" in lower,
                ruleset,
                "table-selectors-contract",
                "Generated table export scripts should expose selectors for output-schema review.",
                "EXPORT_TASK_ERROR",
            )
        if has_image_export:
            findings += _require(
                "MAX_PIXELS" in text or "maxPixels" in text,
                ruleset,
                "max-pixels-budget",
                "Generated image export scripts should expose maxPixels/MAX_PIXELS for quota review.",
                "QUOTA_OR_TIMEOUT",
                retryable=True,
            )
    if "task.start(" in lower or ".start()" in lower:
        findings += _require(
            "def main(" in lower and "if __name__" in lower,
            ruleset,
            "main-guard-for-task-start",
            "Scripts that start export tasks should do so through a main() guarded entrypoint.",
            "EXPORT_TASK_ERROR",
        )
    if "getinfo(" in lower:
        findings.append(
            Finding(
                "warning",
                "generated-script-getinfo",
                "Generated scripts should avoid getInfo() outside bounded preflight/debug probes.",
                hint="Prefer server-side reducers, metadata properties, exports, or harness preflight.",
                category="UNSAFE_GETINFO",
                rule_id=f"{ruleset}.generated-script-getinfo",
                ruleset=ruleset,
                retryable=False,
            )
        )
    return findings


def _optical_index(text: str, lower: str) -> list[Finding]:
    ruleset = "optical_index"
    findings: list[Finding] = []
    findings += _require(
        "filterdate" in lower,
        ruleset,
        "optical-date-filter",
        "Optical index workflow needs filterDate.",
        "VALIDATION_ERROR",
    )
    findings += _require(
        "filterbounds" in lower or "region=" in lower,
        ruleset,
        "optical-region-filter",
        "Optical index workflow needs filterBounds or an explicit export region.",
        "GEOMETRY_ERROR",
        retryable=True,
    )
    findings += _require(
        "scl" in lower or "qa_pixel" in lower or "cloud" in lower or "qa60" in lower,
        ruleset,
        "optical-cloud-or-qa-mask",
        "Optical index workflow needs a cloud or QA masking strategy.",
        "EMPTY_COLLECTION",
        retryable=True,
    )
    findings += _require(
        "scale=" in lower or "scale" in text,
        ruleset,
        "optical-scale",
        "Reducer/export scale is required.",
        "REDUCER_SCALE_ERROR",
        retryable=True,
    )
    if "getinfo(" in lower:
        findings.append(
            Finding(
                "error",
                "unsafe-large-getinfo",
                "Optical workflow contains getInfo(), which is unsafe for large collections.",
                hint="Export server-side objects or write metadata properties instead.",
                category="UNSAFE_GETINFO",
                rule_id=f"{ruleset}.unsafe-large-getinfo",
                ruleset=ruleset,
                retryable=False,
            )
        )
    return findings


def _vegetation_index_ndvi(text: str, lower: str) -> list[Finding]:
    ruleset = "vegetation_index_ndvi"
    findings: list[Finding] = []
    findings += _require(
        '"B8"' in text and '"B4"' in text or "'B8'" in text and "'B4'" in text or "sr_b5" in lower and "sr_b4" in lower,
        ruleset,
        "ndvi-nir-red-bands",
        "NDVI must use an NIR band and a red band.",
        "BAND_NOT_FOUND",
    )
    findings += _require(
        "ndvi" in lower,
        ruleset,
        "ndvi-output-name",
        "NDVI workflow should name the derived band or output field NDVI.",
        "VALIDATION_ERROR",
    )
    return findings


def _water_index_ndwi(text: str, lower: str) -> list[Finding]:
    ruleset = "water_index_ndwi"
    findings: list[Finding] = []
    has_green = any(band in text for band in ('"B3"', "'B3'", '"SR_B3"', "'SR_B3'")) or "sr_b3" in lower
    has_nir_or_swir = (
        any(band in text for band in ('"B8"', "'B8'", '"B11"', "'B11'", '"SR_B5"', "'SR_B5'", '"SR_B6"', "'SR_B6'"))
        or "sr_b5" in lower
        or "sr_b6" in lower
    )
    findings += _require(has_green, ruleset, "ndwi-green-band", "NDWI/MNDWI must use a green band.", "BAND_NOT_FOUND")
    findings += _require(
        has_nir_or_swir,
        ruleset,
        "ndwi-nir-or-swir-band",
        "NDWI/MNDWI must use NIR or SWIR with green.",
        "BAND_NOT_FOUND",
    )
    findings += _require(
        "ndwi" in lower or "mndwi" in lower,
        ruleset,
        "ndwi-output-name",
        "Water index workflow should name the derived band or output field NDWI/MNDWI.",
        "VALIDATION_ERROR",
    )
    return findings


def _builtup_index_ndbi(text: str, lower: str) -> list[Finding]:
    ruleset = "builtup_index_ndbi"
    findings: list[Finding] = []
    has_swir = any(band in text for band in ('"B11"', "'B11'", '"SR_B6"', "'SR_B6'")) or "sr_b6" in lower
    has_nir = any(band in text for band in ('"B8"', "'B8'", '"SR_B5"', "'SR_B5'")) or "sr_b5" in lower
    findings += _require(has_swir, ruleset, "ndbi-swir-band", "NDBI must use a SWIR band.", "BAND_NOT_FOUND")
    findings += _require(has_nir, ruleset, "ndbi-nir-band", "NDBI must use an NIR band.", "BAND_NOT_FOUND")
    findings += _require(
        "ndbi" in lower,
        ruleset,
        "ndbi-output-name",
        "NDBI workflow should name the derived band or output field NDBI.",
        "VALIDATION_ERROR",
    )
    return findings


def _sentinel2_ndvi(text: str, lower: str) -> list[Finding]:
    ruleset = "sentinel2_ndvi_monthly_zonal"
    findings: list[Finding] = []
    findings += _require('"B8"' in text and '"B4"' in text, ruleset, "s2-ndvi-bands", "Sentinel-2 NDVI must use B8 NIR and B4 red bands.", "BAND_NOT_FOUND")
    findings += _require("filterdate" in lower, ruleset, "s2-date-filter", "Sentinel-2 workflow needs filterDate.", "VALIDATION_ERROR")
    findings += _require("filterbounds" in lower or "region=" in lower, ruleset, "s2-region-filter", "Sentinel-2 workflow needs explicit region filtering or export region.", "GEOMETRY_ERROR", retryable=True)
    findings += _require("scl" in lower or "cloud" in lower or "qa60" in lower, ruleset, "s2-cloud-mask", "Sentinel-2 NDVI workflow needs an explicit cloud masking strategy.", "EMPTY_COLLECTION", retryable=True)
    has_monthly_window = (
        "sequence(1, 12)" in lower
        or "advance(1, \"month\")" in lower
        or "advance(1, 'month')" in lower
        or "CADENCE_DAYS" in text
        or "SMOKE_MONTH" in text
        or ("START_DATE" in text and "END_DATE" in text and "month" in lower)
    )
    findings += _require(has_monthly_window, ruleset, "s2-monthly-aggregation", "Sentinel-2 NDVI workflow must explicitly aggregate by month or another reviewed cadence.", "VALIDATION_ERROR")
    findings += _require("scale=" in lower or "scale" in text, ruleset, "s2-scale", "Reducer/export scale is required.", "REDUCER_SCALE_ERROR", retryable=True)
    findings += _require("selectors=" in lower, ruleset, "s2-output-schema", "CSV export must define selectors for a stable output schema.", "EXPORT_TASK_ERROR")
    findings += _require("image_count" in lower, ruleset, "s2-image-count", "Monthly statistics must expose image_count for auditability.", "EMPTY_COLLECTION", retryable=True)
    if "getinfo(" in lower:
        findings.append(
            Finding(
                "error",
                "unsafe-large-getinfo",
                "Sentinel-2 workflow contains getInfo(), which is unsafe for large collections.",
                hint="Export server-side objects or write metadata properties instead.",
                category="UNSAFE_GETINFO",
                rule_id=f"{ruleset}.unsafe-large-getinfo",
                ruleset=ruleset,
                retryable=False,
            )
        )
    return findings


def _landsat_lst(text: str, lower: str, ruleset: str = "landsat_lst") -> list[Finding]:
    findings: list[Finding] = []
    findings += _require("st_b10" in lower, ruleset, "landsat-st-b10", "Landsat LST workflow must use ST_B10.", "BAND_NOT_FOUND")
    findings += _require("0.00341802" in text and "149.0" in text, ruleset, "landsat-lst-scale-offset", "Landsat Collection 2 ST_B10 needs scale 0.00341802 and offset 149.0.", "VALIDATION_ERROR")
    findings += _require("qa_pixel" in lower, ruleset, "landsat-qa-pixel", "Landsat LST workflow needs QA_PIXEL masking.", "EMPTY_COLLECTION", retryable=True)
    findings += _require("filterdate" in lower, ruleset, "landsat-date-filter", "Landsat workflow needs filterDate.", "VALIDATION_ERROR")
    findings += _require("filterbounds" in lower, ruleset, "landsat-region-filter", "Landsat workflow needs filterBounds.", "GEOMETRY_ERROR", retryable=True)
    return findings


def _sentinel1_flood(text: str, lower: str) -> list[Finding]:
    ruleset = "sentinel1_flood_before_after"
    findings: list[Finding] = []
    findings += _require("copernicus/s1_grd" in lower, ruleset, "s1-dataset", "Sentinel-1 flood workflow must use COPERNICUS/S1_GRD.", "DATASET_NOT_FOUND")
    findings += _require("instrumentmode" in lower and "iw" in lower, ruleset, "s1-iw", "Filter Sentinel-1 to IW mode.", "VALIDATION_ERROR")
    findings += _require("transmitterreceiverpolarisation" in lower and ("vv" in lower or "vh" in lower), ruleset, "s1-polarization", "Filter Sentinel-1 by VV or VH polarization.", "BAND_NOT_FOUND")
    findings += _require("before" in lower and "after" in lower, ruleset, "s1-before-after", "Flood workflow must explicitly define before and after windows.", "VALIDATION_ERROR")
    findings += _require("divide" in lower or "subtract" in lower or "ratio" in lower, ruleset, "s1-change-metric", "Flood workflow needs an explicit change metric.", "VALIDATION_ERROR")
    return findings


def _export_table_csv(text: str, lower: str) -> list[Finding]:
    ruleset = "export_table_csv"
    findings: list[Finding] = []
    findings += _require("export.table.todrive" in lower or "ee.batch.export.table.todrive" in lower, ruleset, "table-export-call", "Workflow must use Export.table.toDrive for CSV table output.", "EXPORT_TASK_ERROR")
    findings += _require("fileformat=\"csv\"" in lower or "fileformat='csv'" in lower, ruleset, "csv-format", "CSV export must set fileFormat='CSV'.", "EXPORT_TASK_ERROR")
    findings += _require("description=" in lower, ruleset, "export-description", "Export task needs a stable description.", "EXPORT_TASK_ERROR")
    findings += _require("selectors=" in lower, ruleset, "export-selectors", "CSV export should specify selectors.", "EXPORT_TASK_ERROR")
    return findings


def _export_image_geotiff(text: str, lower: str) -> list[Finding]:
    ruleset = "export_image_geotiff"
    findings: list[Finding] = []
    findings += _require(
        "export.image.todrive" in lower or "ee.batch.export.image.todrive" in lower,
        ruleset,
        "image-export-call",
        "Workflow must use Export.image.toDrive for GeoTIFF image output.",
        "EXPORT_TASK_ERROR",
    )
    findings += _require("region=" in lower, ruleset, "image-export-region", "Image export must set region.", "GEOMETRY_ERROR")
    findings += _require(
        "scale=" in lower or "scale" in text,
        ruleset,
        "image-export-scale",
        "Image export must set scale.",
        "REDUCER_SCALE_ERROR",
        retryable=True,
    )
    findings += _require(
        "maxpixels" in lower or "max_pixels" in lower,
        ruleset,
        "image-export-maxpixels",
        "Image export should set maxPixels/max_pixels.",
        "QUOTA_OR_TIMEOUT",
        retryable=True,
    )
    findings += _require(
        "fileformat=\"geotiff\"" in lower or "fileformat='geotiff'" in lower or "fileformat=\"tif\"" in lower,
        ruleset,
        "geotiff-format",
        "GeoTIFF export must set fileFormat='GeoTIFF'.",
        "EXPORT_TASK_ERROR",
    )
    return findings


def _dynamic_world_landcover_ndvi(text: str, lower: str) -> list[Finding]:
    ruleset = "dynamic_world_landcover_ndvi"
    findings: list[Finding] = []
    findings += _require(
        "google/dynamicworld/v1" in lower,
        ruleset,
        "dynamic-world-dataset",
        "Land-cover-aware NDVI must document/use GOOGLE/DYNAMICWORLD/V1.",
        "DATASET_NOT_FOUND",
    )
    findings += _require(
        '"label"' in text or "'label'" in text,
        ruleset,
        "dynamic-world-label",
        "Dynamic World workflow must reference the label band for schema validation.",
        "NO_LANDCOVER_LABEL",
    )
    for band in ("water", "trees", "grass", "shrub_and_scrub", "built", "bare"):
        findings += _require(
            f'"{band}"' in text or f"'{band}'" in text,
            ruleset,
            f"dynamic-world-{band}",
            f"Dynamic World workflow must reference probability band {band}.",
            "NO_PROBABILITY_BANDS",
        )
    findings += _require(
        "dynamic_world_probability_threshold" in lower,
        ruleset,
        "dynamic-world-threshold",
        "Probability threshold must be named and exported for reproducibility.",
        "VALIDATION_ERROR",
    )
    findings += _require(
        "water_fraction" in lower and "built_fraction" in lower and "vegetation_fraction" in lower,
        ruleset,
        "class-fractions",
        "Output must include land-cover class fractions for interpretation.",
        "CLASS_MASK_EMPTY",
        retryable=True,
    )
    findings += _require(
        "all_surface_mean_ndvi" in lower and "non_water_mean_ndvi" in lower and "vegetation_mean_ndvi" in lower,
        ruleset,
        "diagnostic-ndvi-fields",
        "Output must compare all-surface, non-water, and vegetation NDVI.",
        "VALIDATION_ERROR",
    )
    findings += _require(
        "preflight_required_before_export" in lower,
        ruleset,
        "preflight-required-marker",
        "Live export must be run through a preflight-aware command.",
        "PREFLIGHT_REQUIRED",
        retryable=True,
    )
    findings += _require(
        "selectors=" in lower,
        ruleset,
        "explicit-selectors",
        "Land-cover-aware CSV export must use explicit selectors.",
        "EXPORT_TASK_ERROR",
    )
    return findings


def _dynamic_world_landcover(text: str, lower: str) -> list[Finding]:
    ruleset = "dynamic_world_landcover"
    findings: list[Finding] = []
    findings += _require(
        "google/dynamicworld/v1" in lower,
        ruleset,
        "dynamic-world-dataset",
        "Dynamic World land-cover summary must use GOOGLE/DYNAMICWORLD/V1.",
        "DATASET_NOT_FOUND",
    )
    findings += _require(
        '"label"' in text or "'label'" in text,
        ruleset,
        "dynamic-world-label",
        "Dynamic World summary must use the label band.",
        "NO_LANDCOVER_LABEL",
    )
    findings += _require(
        "filterdate" in lower,
        ruleset,
        "dynamic-world-date-filter",
        "Dynamic World summary must use filterDate.",
        "VALIDATION_ERROR",
    )
    findings += _require(
        "filterbounds" in lower,
        ruleset,
        "dynamic-world-region-filter",
        "Dynamic World summary must use filterBounds.",
        "GEOMETRY_ERROR",
        retryable=True,
    )
    findings += _require(
        "ee.image.pixelarea" in lower and "area_m2" in lower,
        ruleset,
        "dynamic-world-area-summary",
        "Dynamic World summary should report area_m2 by class.",
        "VALIDATION_ERROR",
    )
    findings += _require(
        "fraction" in lower,
        ruleset,
        "dynamic-world-fraction",
        "Dynamic World summary should report class fractions.",
        "VALIDATION_ERROR",
    )
    findings += _require(
        "selectors=" in lower,
        ruleset,
        "explicit-selectors",
        "Dynamic World CSV export must use explicit selectors.",
        "EXPORT_TASK_ERROR",
    )
    return findings
